version: '3'

services: 
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - 3306:3306
    volumes:
       - db_data:/var/lib/mysql

volumes: 
  db_data: {}